name: Deploy

on:
  push:
    branches: [master]

jobs:
  update-env-file:
    name: Update .env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update .env file
        run: |
          echo "REACT_APP_ENVIRONMENT=prod" > .env
          echo "REACT_APP_BASE_API_URL=https://api.metahunt.gg" >> .env
          echo "REACT_APP_OXBL_APP=${{ secrets.REACT_APP_OXBL_APP }}" >> .env
          echo "REACT_APP_DISCORD_LINK=${{ secrets.REACT_APP_DISCORD_LINK }}" >> .env

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .env
          git commit -m "Update .env file with new secrets"
          git push https://github-actions:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build the app
        run: npm run build

      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id ${{ vars.AWS_GITHUB_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_GITHUB_ACCESS_SECRET }}
          aws configure set default.region us-east-1
          aws s3 cp ./build s3://${{ vars.AWS_S3_BUCKET }}/ --recursive --exclude "*.html"
          aws s3 cp ./build s3://${{ vars.AWS_S3_BUCKET }}/ --recursive --exclude "*" --include "*.html" --cache-control "public, must-revalidate, proxy-revalidate, max-age=0"
